// <auto-generated />
namespace MFI.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addClientProvider : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addClientProvider));
        
        string IMigrationMetadata.Id
        {
            get { return "201910122308323_addClientProvider"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
